import os
import json
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from .database import engine, Base
from .routers import auth, drafts, accounts, analytics, campaigns, oauth, content_ideas
from .routers.content_ideas import ContentIdea  # noqa: F401 – ensures model is registered before create_all
from .skills.cloud_deployment import get_cloud_deployment_status
from .skills.devops_tooling import run_system_health_audit

from sqlalchemy import inspect, text

# Create SQLite tables on startup (must run AFTER all models are imported)
Base.metadata.create_all(bind=engine)

# Auto-migrate SQLite columns if table was created previously without new fields
def run_db_migrations():
    with engine.connect() as conn:
        inspector = inspect(engine)
        if "prompts" in inspector.get_table_names():
            columns = [c["name"] for c in inspector.get_columns("prompts")]
            if "campaign_id" not in columns:
                conn.execute(text("ALTER TABLE prompts ADD COLUMN campaign_id INTEGER REFERENCES campaigns(id)"))
                conn.commit()
        if "drafts" in inspector.get_table_names():
            columns = [c["name"] for c in inspector.get_columns("drafts")]
            if "campaign_id" not in columns:
                conn.execute(text("ALTER TABLE drafts ADD COLUMN campaign_id INTEGER REFERENCES campaigns(id)"))
            if "scheduled_at" not in columns:
                conn.execute(text("ALTER TABLE drafts ADD COLUMN scheduled_at DATETIME"))
            conn.commit()
        if "content_ideas" in inspector.get_table_names():
            columns = [c["name"] for c in inspector.get_columns("content_ideas")]
            if "media_url" not in columns:
                conn.execute(text("ALTER TABLE content_ideas ADD COLUMN media_url TEXT"))
            if "link_url" not in columns:
                conn.execute(text("ALTER TABLE content_ideas ADD COLUMN link_url TEXT"))
            if "first_comment" not in columns:
                conn.execute(text("ALTER TABLE content_ideas ADD COLUMN first_comment TEXT"))
            if "is_starred" not in columns:
                conn.execute(text("ALTER TABLE content_ideas ADD COLUMN is_starred BOOLEAN DEFAULT 0"))
            conn.commit()

run_db_migrations()

app = FastAPI(
    title="AI-Powered Social Media Content Generation System API",
    description="Backend API for managing prompts, drafts, accounts, campaigns, and analytics tracking.",
    version="1.0.0"
)

# CORS configuration
# Allow React frontend (Vite/Next.js) to connect
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Adjust for specific domains in production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Create static asset directories if they don't exist
os.makedirs("static", exist_ok=True)
os.makedirs(os.path.join("static", "media"), exist_ok=True)

# Mount static folder
app.mount("/static", StaticFiles(directory="static"), name="static")

# Register routers
app.include_router(auth.router)
app.include_router(drafts.router)
app.include_router(accounts.router)
app.include_router(analytics.router)
app.include_router(campaigns.router)
app.include_router(oauth.router)
app.include_router(content_ideas.router)

@app.get("/")
def read_root():
    return {"message": "AI-Powered Social Media Content Generation MVC API is active."}

@app.get("/api/notifications")
def get_notifications():
    """
    Polled by the frontend to display notifications generated by life-cycle events.
    """
    notifications_log = os.path.join("static", "notifications.json")
    if os.path.exists(notifications_log):
        try:
            with open(notifications_log, "r") as f:
                return json.load(f)
        except Exception:
            pass
    return []

@app.get("/api/system/health")
def get_system_health():
    """
    Skill 10: DevOps / Full-Stack Support diagnostic health check endpoint.
    """
    return run_system_health_audit()

@app.get("/api/system/cloud-status")
def get_cloud_status():
    """
    Skill 8: Cloud & Deployment container autoscaling and CI/CD status endpoint.
    """
    return get_cloud_deployment_status()

